author:
  name: "Сурен Хоренян"
  bio: |
    Python Backend Developer.
    Open Source Contributor.
    Преподаватель по веб-разработке на Python.
  links:
    - name: "Обо мне"
      url: "https://www.mahenzon.ru"
      icon: "homepage"
    - name: "GitHub"
      url: "https://github.com/mahenzon"
      icon: "github"
    - name: "Телеграм"
      url: "https://t.me/Khorenyan"
      icon: "telegram"
    - name: "YouTube"
      url: "https://www.youtube.com/@SurenKhorenyan"
      icon: "youtube"

og:
  title: "Python ПРОрыв - Веб разработка на Python."
  description: "Курс. Полный цикл разработки веб разработки на Python с нуля до продакшн."

course:
  title: "Python ПРОрыв"
  subtitle: "Разработка веб-приложений на Python"
  description: |
    Комплексный курс по веб-разработке на Python.
    
    Изучите создание современных веб-приложений с нуля до продакшена.
    Практические проекты и поддержка Сурена на всём пути обучения.
  features:
    - "Асинхронное обучение"
    - "Практические проекты"
    - "Поддержка Сурена"
    - "Реальные кейсы из индустрии"

statistics:
  numberOfStudents: 75
